TARGET := genomorph

CXX := clang++

SRC_DIR := src
GEN_DIR := generators
INC_DIR := include
BUILD_DIR := build
BIN_DIR := bin

CXXFLAGS := -std=c++20 -Wall -Wextra -O2 -I$(INC_DIR)

SRCS := \
	src/main.cpp \
	generators/genomeGenerator.cpp \
	generators/regionGenerator.cpp

OBJS := $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(SRCS))

all: $(BIN_DIR)/$(TARGET)

$(BIN_DIR)/$(TARGET): $(OBJS)
	@mkdir -p $(BIN_DIR)
	$(CXX) $(OBJS) -o $@

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR)

rebuild: clean all

.PHONY: all clean rebuild
